# Generated by Django 3.2.7 on 2021-09-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_Name', models.CharField(max_length=100)),
                ('Branch_Path', models.CharField(max_length=200)),
                ('Branch_Status', models.BooleanField(default=False)),
                ('Branch_Message', models.CharField(max_length=100)),
                ('Branch_Address', models.CharField(max_length=100)),
                ('Branch_Contact1', models.CharField(max_length=20)),
                ('Branch_Contact2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exchange_Name', models.CharField(max_length=50)),
                ('Exchange_Status', models.BooleanField(default=False)),
                ('Exchange_Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institutional_Capital', models.IntegerField()),
                ('Institutional_Assets', models.IntegerField()),
                ('Institutional_Deposits', models.IntegerField()),
                ('Institutional_Members', models.IntegerField()),
                ('Institutional_Reserve_Fund', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Name', models.CharField(max_length=50)),
                ('Loan_Status', models.BooleanField(default=False)),
                ('Loan_Message', models.CharField(max_length=100)),
                ('Loan_Intrestrate', models.CharField(max_length=20)),
                ('Loan_Period', models.CharField(max_length=20)),
                ('Loan_Features', models.TextField(max_length=500)),
                ('Loan_TC', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice_Name', models.CharField(max_length=50)),
                ('Notice_Content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saving_Name', models.CharField(max_length=30)),
                ('Saving_Status', models.BooleanField(default=False)),
                ('Saving_Message', models.CharField(max_length=100)),
                ('Saving_IntrestRate', models.CharField(max_length=20)),
                ('Saving_Period', models.CharField(max_length=20)),
                ('Saving_Features', models.TextField(max_length=500)),
                ('Saving_TC', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_Name', models.CharField(max_length=50)),
                ('Services_Status', models.BooleanField(default=False)),
                ('Services_Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exchange_Name', models.CharField(max_length=50)),
                ('Exchange_Status', models.BooleanField(default=False)),
                ('Exchange_Message', models.CharField(max_length=100)),
            ],
        ),
    ]
