# Generated by Django 3.2.7 on 2021-09-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_branch_exchangerate_institutionalprofile_loan_notices_saving_services_successstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saving',
            old_name='Saving_IntrestRate',
            new_name='Saving_Intrestrate',
        ),
    ]
