# Generated by Django 3.2.7 on 2021-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_saving_intrestrate_saving_saving_intrestrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successstory',
            old_name='Exchange_Message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='Exchange_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='Exchange_Status',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='notices',
            name='Notices_Status',
            field=models.BooleanField(default=False),
        ),
    ]
