# Generated by Django 3.2.7 on 2021-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210907_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Branch_Path',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Slider_Path',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
