# Generated by Django 3.2.7 on 2021-09-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210907_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notices',
            old_name='Notices_Status',
            new_name='Notice_Status',
        ),
    ]
