# Generated by Django 3.2.7 on 2021-09-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_notices_status_notices_notice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Branch_Message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='Exchange_Message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Loan_Message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notices',
            name='Notice_Content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saving',
            name='Saving_Message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_Message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Slide_Message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='Message',
            field=models.TextField(max_length=100),
        ),
    ]
