# Generated by Django 3.2.7 on 2021-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20210907_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='LastName',
            field=models.CharField(default='ERROR', max_length=50),
        ),
    ]
