# Generated by Django 3.2.7 on 2021-09-07 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kyc_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='DOB',
            new_name='DOB_AD',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='GfName',
        ),
        migrations.AddField(
            model_name='kyc',
            name='AccountFingerL',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kyc',
            name='AccountFingerR',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kyc',
            name='AccountPhoto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kyc',
            name='ApplicantSignature',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kyc',
            name='DOB_BS',
            field=models.DateField(default=datetime.date(2021, 9, 7)),
        ),
        migrations.AddField(
            model_name='kyc',
            name='GrandFatherName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='GuardianAddress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='GuardianName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='GuardianRelation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='GuardianTelephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='NomineeAddress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='NomineeMembershipno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='NomineeName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='NomineeRelation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='NomineeTelephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='Occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='OrganizationName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_Country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_District',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_Email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_House',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_Mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_OfficePhone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_Phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_Tole',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_VDC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_Ward',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='P_Zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_Country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_District',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_Email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_House',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_Mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_OfficePhone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_Phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_Tole',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_VDC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_Ward',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='T_Zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='FatherName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='FirstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='LastName',
            field=models.CharField(max_length=50),
        ),
    ]
