# Generated by Django 3.2.7 on 2021-09-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_auto_20210907_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
