# Generated by Django 3.2.7 on 2021-09-10 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kyc_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='DOB_AD',
            field=models.DateField(default=datetime.date(2021, 9, 10)),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='DOB_BS',
            field=models.DateField(default=datetime.date(2021, 9, 10)),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='P_Country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='P_District',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='P_Email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='P_Mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='P_VDC',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='P_Zone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='T_Email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
